# Generated by Django 3.1.6 on 2021-02-11 10:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.TextField(blank=True, null=True)),
                ('bedRooms', models.IntegerField(blank=True, null=True)),
                ('bathRooms', models.IntegerField(blank=True, null=True)),
                ('lift', models.BooleanField()),
                ('carParking', models.BooleanField()),
                ('twoWheelerParking', models.BooleanField()),
                ('security', models.BooleanField()),
                ('cctv', models.BooleanField()),
                ('available_from', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(0, 'RENT'), (1, 'SALE')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertytype')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertytype')),
                ('property_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertytype'),
        ),
    ]
