# Generated by Django 3.1.6 on 2021-02-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(choices=[('rent', 'RENT'), ('sale', 'SALE')], max_length=20),
        ),
    ]
