# Generated by Django 3.1.6 on 2021-02-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20210215_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='property_type',
        ),
    ]
