# Generated by Django 3.1.6 on 2021-02-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_auto_20210216_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertystatus',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertystatus',
            name='text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
