# Generated by Django 3.1.6 on 2021-02-17 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_auto_20210216_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('on-going', 'ON-GOING'), ('follow', 'FOLLOW')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SiteVists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('pickUpLocation', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bookings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.bookings')),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.sitevists'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
